routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Http\Controllers\Frontend as Frontend;
use App\Http\Controllers\Auth as Auth;


Route::get('/', [Frontend\HomeController::class, 'index'])->name('home.index');
Route::get('about', [Frontend\AboutController::class, 'index'])->name('about.index');
Route::get('page/{slug}', [Frontend\PageController::class, 'show'])->name('user.page.index');
Route::get('explore', [Frontend\ExploreController::class, 'index'])->name('explore.index');
Route::get('gym', [Frontend\GymController::class, 'index'])->name('user.gym.index');
Route::get('how-it-works', [Frontend\HowItWorksController::class, 'index'])->name('how-it-works.index');
Route::get('inner-gym', [Frontend\InnerGymController::class, 'index'])->name('inner-gym.index');
Route::get('join-us', [Frontend\JoinUsController::class, 'index'])->name('join-us.index');
Route::get('pricing', [Frontend\PricingController::class, 'index'])->name('pricing.index');
Route::get('trainer-detail', [Frontend\TrainerDetailController::class, 'index'])->name('trainer-detail.index');

Route::get('blog', [Frontend\blogController::class, 'index'])->name('blog.index');
Route::get('single-blog/{id}', [Frontend\blogController::class, 'show'])->name('single-blog.show');
Route::get('blog/category/{id}', [Frontend\blogController::class, 'category'])->name('blog.category');
Route::get('blog/tag/{id}', [Frontend\blogController::class, 'tags'])->name('blog.tag');

Route::get('gym/category/{id}', [Frontend\GymController::class, 'category'])->name('gym.category');
Route::get('inner-gym/{id}', [Frontend\GymController::class, 'show'])->name('inner-gym.show');


Route::get('trainer-detail/{id}', [Frontend\HomeController::class, 'show'])->name('trainer-detail.show');

Route::get('/register', [Auth\RegisterController::class, 'create'])->name('register.create');
Route::post('register', [Auth\RegisterController::class, 'store'])->name('register.store');

Route::get('/login', [Auth\LoginController::class, 'create'])->name('login.create');
Route::post('login-store', [Auth\LoginController::class, 'store'])->name('login.store');
Route::get('/logout', [Auth\LoginController::class, 'logout'])->name('logout');


Route::post('review', [Frontend\ReviewController::class, 'store'])->name('review.store');

Route::post('class-schedule/detail',[Frontend\HomeController::class,'classScheduleDetail'])->name('class-schedule.detail');

Route::post('class-schedule/detail/date',[Frontend\HomeController::class,'classScheduleDetailDate'])->name('class-schedule.detail.date');

//All Admin Routes


use App\Http\Controllers\Admin as Admin;

Route::get('admin/home', [Admin\HomeController::class, 'index'])->name('admin.home');
Route::resource('admin/category', Admin\CategoryController::class);
Route::resource('admin/roles', Admin\RoleController::class);
Route::resource('admin/user', Admin\UserController::class);
Route::resource('admin/gym-category', Admin\GymCategoryController::class);
Route::resource('admin/tag', Admin\TagController::class);
Route::resource('admin/post', Admin\PostController::class);
Route::resource('admin/gym', Admin\GymController::class);
Route::resource('admin/instructor', Admin\InstructorController::class);
Route::resource('admin/page', Admin\PageController::class);
Route::resource('admin/reviews', Admin\ReviewController::class);
Route::resource('admin/classes', Admin\UClassController::class);
Route::resource('admin/class-schedule', Admin\ClassScheduleController::class);

Route::get('admin/role/matrix', [Admin\RoleController::class,'rolesPermissions'])->name('admin.roles.matrix.index');

Route::post('admin/role/matrix/store', [Admin\RoleController::class,'rolesPermissionsStore'])->name('admin.roles.matrix.store');

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    @include('admin/layouts/head')

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    @include('admin/layouts/header')

    @include('admin/layouts/sidebar')

    @section('main-content')

    @show


    @include('admin/layouts/footer')

</div>
<!-- ./wrapper -->

</body>
</html>

resources/views/admin/home.blade.php
@extends('admin/app')

@section('headSection')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
           folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">
@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Dashboard</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v1</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-4 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{ $postCount }}</h3>

                                <p>Posts</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="{{ route('post.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-4 col-6">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>{{ $reviewsCount }}</h3>

                                <p>Reviews</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="{{ route('reviews.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-4 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{ $usersCount }}</h3>

                                <p>User Registrations</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="{{ route('user.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->

                    <!-- ./col -->
                    <div class="col-lg-4 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{ $gymCount }}</h3>

                                <p>Gym</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="{{ route('gym.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->

                    <!-- ./col -->
                    <div class="col-lg-4 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{ $instructorCount }}</h3>

                                <p>Instructor</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="{{ route('instructor.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->

                    <!-- ./col -->
                </div>
                <!-- /.row -->
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                </div>
            </div>
        </section>
    </div>
    <!-- /.content-wrapper -->



@endsection

@section('footerSection')
    <!-- jQuery 3 -->
    <script src="{{ asset('admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- DataTables -->
    <script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('admin/dist/js/demo.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection