routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Http\Controllers\Frontend as Frontend;
use App\Http\Controllers\Auth as Auth;


Route::get('/', [Frontend\HomeController::class, 'index'])->name('home.index');
Route::get('about', [Frontend\AboutController::class, 'index'])->name('about.index');
Route::get('page/{slug}', [Frontend\PageController::class, 'show'])->name('user.page.index');
Route::get('explore', [Frontend\ExploreController::class, 'index'])->name('explore.index');
Route::get('gym', [Frontend\GymController::class, 'index'])->name('user.gym.index');
Route::get('how-it-works', [Frontend\HowItWorksController::class, 'index'])->name('how-it-works.index');
Route::get('inner-gym', [Frontend\InnerGymController::class, 'index'])->name('inner-gym.index');
Route::get('join-us', [Frontend\JoinUsController::class, 'index'])->name('join-us.index');
Route::get('pricing', [Frontend\PricingController::class, 'index'])->name('pricing.index');
Route::get('trainer-detail', [Frontend\TrainerDetailController::class, 'index'])->name('trainer-detail.index');

Route::get('blog', [Frontend\blogController::class, 'index'])->name('blog.index');
Route::get('single-blog/{id}', [Frontend\blogController::class, 'show'])->name('single-blog.show');
Route::get('blog/category/{id}', [Frontend\blogController::class, 'category'])->name('blog.category');
Route::get('blog/tag/{id}', [Frontend\blogController::class, 'tags'])->name('blog.tag');

Route::get('gym/category/{id}', [Frontend\GymController::class, 'category'])->name('gym.category');
Route::get('inner-gym/{id}', [Frontend\GymController::class, 'show'])->name('inner-gym.show');


Route::get('trainer-detail/{id}', [Frontend\HomeController::class, 'show'])->name('trainer-detail.show');

Route::get('/register', [Auth\RegisterController::class, 'create'])->name('register.create');
Route::post('register', [Auth\RegisterController::class, 'store'])->name('register.store');

Route::get('/login', [Auth\LoginController::class, 'create'])->name('login.create');
Route::post('login-store', [Auth\LoginController::class, 'store'])->name('login.store');
Route::get('/logout', [Auth\LoginController::class, 'logout'])->name('logout');


Route::post('review', [Frontend\ReviewController::class, 'store'])->name('review.store');

Route::post('class-schedule/detail',[Frontend\HomeController::class,'classScheduleDetail'])->name('class-schedule.detail');

Route::post('class-schedule/detail/date',[Frontend\HomeController::class,'classScheduleDetailDate'])->name('class-schedule.detail.date');

//All Admin Routes


use App\Http\Controllers\Admin as Admin;

Route::get('admin/home', [Admin\HomeController::class, 'index'])->name('admin.home');
Route::resource('admin/category', Admin\CategoryController::class);
Route::resource('admin/roles', Admin\RoleController::class);
Route::resource('admin/user', Admin\UserController::class);
Route::resource('admin/gym-category', Admin\GymCategoryController::class);
Route::resource('admin/tag', Admin\TagController::class);
Route::resource('admin/post', Admin\PostController::class);
Route::resource('admin/gym', Admin\GymController::class);
Route::resource('admin/instructor', Admin\InstructorController::class);
Route::resource('admin/page', Admin\PageController::class);
Route::resource('admin/reviews', Admin\ReviewController::class);
Route::resource('admin/classes', Admin\UClassController::class);
Route::resource('admin/class-schedule', Admin\ClassScheduleController::class);

Route::get('admin/role/matrix', [Admin\RoleController::class,'rolesPermissions'])->name('admin.roles.matrix.index');

Route::post('admin/role/matrix/store', [Admin\RoleController::class,'rolesPermissionsStore'])->name('admin.roles.matrix.store');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany(Post::class, 'post_tags')->orderBy('created_at', 'DESC')->paginate(5);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:tag-list|tag-create|tag-edit|tag-delete', ['only' => ['index','store']]);
        $this->middleware('permission:tag-create', ['only' => ['create','store']]);
        $this->middleware('permission:tag-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:tag-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        //$tags = tag::orderBy('created_at','DESC')->get();
        return view('admin.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $this->validate($request,[
            'name' => 'required',
            'slug' => 'required',
            ]);
        $tag = new Tag();
        $tag->name = $request->name;
        $tag->slug = $request->slug;
        $tag->save();
        return redirect(route('tag.index'))->with('message', 'Added Tag Successfully!!!!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::where('id',$id)->first();
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'required',
            ]);
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->slug = $request->slug;
        $tag->save();

        return redirect(route('tag.index'))->with('message', 'Edited Tag Successfully!!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::where('id',$id)->delete();
        return redirect()->back()->with('message', 'Deleted Tag Successfully!!!!');
    }
}

resources/views/admin/tag/create.blade.php
@extends('admin.app')

@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">
                            <i class="fa fa-ticket" aria-hidden="true"></i> Tag
                            <small>Create form element</small></h1>

                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('tag.index') }}">Tag Table</a></li>
                            <li class="breadcrumb-item active">Create From</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->


        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit Tag</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" action="{{ route('tag.store') }}" method="post">
                                {{ csrf_field() }}
                                <div class="card-body">
                                    @include('includes.messages')
                                    <div class="form-group">
                                        <label for="name">Tag title</label>
                                        <input type="text" class="form-control" id="name" name="name"
                                               placeholder="Tag Title">

                                    </div>
                                    <div class="form-group">
                                        <label for="slug">Tag Slug</label>
                                        <input type="text" class="form-control" id="slug" name="slug"
                                               placeholder="Slug">
                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href='{{ route('tag.index') }}' class="btn btn-warning">Back</a>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->


                    </div>
                    <!--/.col (left) -->

                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/tag/edit.blade.php
@extends('admin.app')

@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">
                            <i class="fa fa-ticket" aria-hidden="true"></i> Tag
                            <small>Edit</small></h1>

                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('tag.index') }}">Tag Table</a></li>
                            <li class="breadcrumb-item active">Edit From</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->


        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create Tag</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" action="{{ route('tag.update',$tag->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <div class="card-body">
                                    @include('includes.messages')
                                    <div class="form-group">
                                        <label for="name">Tag title</label>
                                        <input type="text" class="form-control" id="name" name="name"
                                               placeholder="Tag Title"    value="{{ $tag->name }}">

                                    </div>
                                    <div class="form-group">
                                        <label for="slug">Tag Slug</label>
                                        <input type="text" class="form-control" id="slug" name="slug"
                                               placeholder="Slug"    value="{{ $tag->slug }}">
                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href='{{ route('tag.index') }}' class="btn btn-warning">Back</a>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->


                    </div>
                    <!--/.col (left) -->

                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/tag/index.blade.php
@extends('admin.app')

@section('headSection')
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection

@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">
                            <i class="fa fa-ticket" aria-hidden="true"></i>Tags
                            <small>Create, Read, Update, Delete</small></h1>

                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
                            <li class="breadcrumb-item active"><a href="{{ route('tag.index') }}">Tags
                                    Table</a></li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->


        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">

                            <div class="card-header">
                                <h3 class="card-title">Tags</h3>
                                @can('tag-create')
                                    <a class='float-right btn btn-success' href="{{ route('tag.create') }}">Add New</a>
                                @endcan
                            </div>

                        @include('includes.messages')
                        <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example2" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>S.No</th>
                                        <th>Tag Name</th>
                                        <th>Slug</th>
                                        @can('tag-edit')
                                            <th>Edit</th>
                                        @endcan
                                        @can('tag-delete')
                                            <th>Delete</th>
                                        @endcan
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($tags as $tag)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $tag->name }}</td>
                                            <td>{{ $tag->slug }}</td>
                                            @can('tag-edit')
                                                <td><a href="{{ route('tag.edit',$tag->id) }}"><span
                                                            class="fa fa-edit"></span></a></td>
                                            @endcan
                                            @can('tag-delete')
                                                <td>
                                                    <form id="delete-form-{{ $tag->id }}" method="post"
                                                          action="{{ route('tag.destroy',$tag->id) }}"
                                                          style="display: none">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                    <a href="" onclick="
                                                        if(confirm('Are you sure, You Want to delete this?'))
                                                        {
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $tag->id }}').submit();
                                                        }
                                                        else{
                                                        event.preventDefault();
                                                        }"><span class="fa fa-trash"></span></a>
                                                </td>
                                            @endcan


                                        </tr>

                                    @endforeach

                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>S.No</th>
                                        <th>Tag Name</th>
                                        <th>Slug</th>
                                        @can('tag-edit')
                                            <th>Edit</th>
                                        @endcan
                                        @can('tag-delete')
                                            <th>Delete</th>
                                        @endcan
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->


                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->


    </div>
    <!-- /.content-wrapper -->
@endsection

@section('footerSection')
    <!-- jQuery -->
    <script src="{{ asset('admin/plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- DataTables -->
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('admin/dist/js/demo.js') }}"></script>
    <script>
        $(function () {
            $('#example2').DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        })
    </script>
@endsection